### ISSUE TITLE
Investigate create_questionnaire method and its usage

### ISSUE THREAD

**Issue by ProfDoof** [ProfDoof/expertiza#1]
There is a method called create_questionnaire used.  Is it used?  There are no immediately apparent calls to it.  The name is wrong (should be just create, but there is another, different create method).  If not, remove create_questionnaire and the tests that test it.  [It is not used, but it assigns a creator ID (instructor of the class) whereas create does not.]

**Comment by isha-bansal0115** [comment]
Completed and pushed the code to E2117 branch
